# PowerShell script that will help you delete sessions that have been disconnected for more than 3 days, generated by ChatGPT :
# Get the current date
$currentDate = Get-Date

# Get disconnected sessions older than 3 days
$disconnectedSessions = Get-RDUserSession | Where-Object { $_.State -eq 'Disconnected' -and ($currentDate - $_.DisconnectTime).Days -gt 3 }

# Delete the sessions
foreach ($session in $disconnectedSessions) {
    Invoke-RDUserLogoff -UnifiedSessionID $session.UnifiedSessionID -Force
}



I apologize for the confusion. If the `Get-RDUserSession` cmdlet doesn't provide the disconnected status, you might need to adjust your approach. Here's an alternative script that uses `quser` command to retrieve disconnected sessions and then calculates the duration to perform the logoff:

```powershell
# Get disconnected sessions using quser
$disconnectedSessions = quser | ForEach-Object {
    $sessionInfo = $_ -split '\s+'
    $username = $sessionInfo[0]
    $sessionState = $sessionInfo[2]
    $sessionIdleTime = [TimeSpan]::Parse($sessionInfo[3])

    if ($sessionState -eq "Disc" -and $sessionIdleTime.TotalDays -gt 3) {
        $username
    }
}

# Log off the disconnected sessions
foreach ($username in $disconnectedSessions) {
    logoff $username /server:your_server_name_or_ip
}
```

Replace `"your_server_name_or_ip"` with the actual name or IP address of your server. This script uses the `quser` command to retrieve session information, and then logs off sessions that are both in a "Disc" (Disconnected) state and have been idle for more than 3 days.

Please ensure you run this script with appropriate permissions and test it in a controlled environment before using it in a production setting.